### ISSUE TITLE
Fallback to English I18N when no local translation is available

### ISSUE THREAD

**Issue by kotcrab** [czyzby/gdx-setup#18]
Currently application will crash if there is no valid key in `pl` bundle but it exists in `en` bundle. In such case it should fallback to English locale. In the future locales might be out of sync - after all we can't know all languages and might not be able to update them ourselves so fallback strategy should be used.

**Comment by czyzby** [comment]
We could move all lines from `nls_en.properties` to `nls.properties`, but the application crashing is sort of the expected behavior: it's easy to track down missing lines this way, and translations that are just kind of half way through are not accepted. I think this should be considered when there are more locales around (more than the current devs are comfortable with).

**Comment by kotcrab** [comment]
I agree, this will become problem when more languages would be added.

**Comment by czyzby** [comment]
After we're done with most planned features (translations become "semi-stable"), we could move the whole `nls_en.properties` file to the bottom of `nls.properties` and proceed it with a comment like this: `# The following bundle lines should be translated:`. But since the application is kind of a work in progress, we can leave it as it is for now to quickly track bugs. After all, you're unlikely to notice that a single tooltip is not translated when adding multiple lines.

**Comment by kotcrab** [comment]
Ok, after it's done CONTRIBUTING.md should be updated as well.

**Comment by czyzby** [comment]
https://github.com/czyzby/gdx-setup/releases/tag/v1.9.2-beta1

**Comment by czyzby** [comment]
Sprawdź, czy nic się nie wywala, zanim ogłosimy się światu. : P

**Comment by czyzby** [comment]
http://www.badlogicgames.com/forum/viewtopic.php?f=17&t=22511
