### ISSUE TITLE
SquidLib-related templates

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-setup#19]
- [x] A simple project. (_How to use SquidLib in my game?_)
- ~~A showcase text-based demo. (_What can be done with SquidLib?_)~~
- [ ] Update project according to the latest `3.0.0-b8` features.

**Comment by tommyettinger** [comment]
OK, here's the simple-ish project. It seems more complicated than it is because I put documentation on almost every line, which hopefully will help someone getting started with the (large, large) library.

https://github.com/tommyettinger/SquidLib-Demos/tree/master/GdxSetup/SquidLibBasicDemo

I needed to comment out a section of the Android project's build.gradle for this to even import into IDEA, which is a half-solution to #20 . There's a problem with the dependency on squidlib-util on HTML; setup downloads the binary .jar but not the sources .jar, and doesn't add squidlib-util as an inherit for GWT (though I don't know if having an inherit on squidlib, the display code, implicitly creates -util's inherit). The setup tool gets SquidLib and RegExodus just fine with only SquidLib checked in the setup, including sources jars for both of them. I hope this is useful!

**Comment by czyzby** [comment]
> The setup tool gets SquidLib and RegExodus just fine with only SquidLib checked in the setup, including sources jars for both of them. I hope this is useful!

You're right, SquidLib dependency did not properly include the whole SquidLib Util. It's fixed now.

As for the Android application, I cannot reproduce your problem. This is one of the templates running in an Android simulator via Android Studio (a.k.a. why `ScreenViewport` is not always the greatest idea):

![android](https://cloud.githubusercontent.com/assets/11707612/15109948/582379c0-15de-11e6-9987-bd305e72f0b1.png)

No changes in the application itself or its Gradle files were required.

> OK, here's the simple-ish project.

I'll look into it, thanks.

**Comment by czyzby** [comment]
Just wanted you to know that demos might include multiple files, not only the core class - if you want to split the next project a little bit (for readability), it's OK. The main class seems rather long, although I understand that it's mostly just the comments.

I tested your project on desktop, GWT and Android (emulator) and it seems to be running just fine. Thanks.

![squid](https://cloud.githubusercontent.com/assets/11707612/15112249/33a614b8-15ed-11e6-9e27-f4f471aefa7d.png)

**Comment by tommyettinger** [comment]
Woohoo! Thanks for adding this. Now it's showcase time...

**Comment by czyzby** [comment]
@tommyettinger Are you planning on preparing a showcase example or is there a working example that I could convert to a project template?

**Comment by tommyettinger** [comment]
I dropped the ball here! I saw your reply on my phone, went to my computer, and immediately forgot what I was doing. I will try to get a showcase example ready in the next few days; I'm not sure what scale it should have but I have an idea of the kinds of things to showcase. **Should the example be created with gdx-setup initially, and would that make it easier to convert it in any way?**

Just some notes for my purposes... I'll want to have several dungeon generators shown, which probably means multiple floors that can be traversed. Each floor might have different filters applied to its color scheme. FOV is definitely going in this, as is pathfinding. I'll use the on-screen controls for Android versions (and iOS if that gets more stable), but those controls have been hard to use during play in my limited testing. I may figure out a way to work other, more unusual, features in, probably using more logic than previous demos have for enemies.

OK, time to get working.

**Comment by czyzby** [comment]
> Should the example be created with gdx-setup initially, and would that make it easier to convert it in any way?

If you have an existing application that would take time to convert, you don't have to recreate it wigh `gdx-setup`, but if you're planning on writing something new, I don't see why not.

Great, thanks.

**Comment by tommyettinger** [comment]
OK, writing the demo I managed to find (and fix) a bug in SquidLib's animation code. I just released a new version (I don't know if Gradle's version ranges handle it, but the new version is `3.0.0-b6` on Maven). This version is an update for `squidlib` to `3.0.0-b6`, `squidlib-util` to `3.0.0-b6`, and `regexodus` to `0.1.5`. I'm not sure where I should request a version bump, if at all. @czyzby , I'll keep working on the demo but I think it should depend on the updated versions; the bug this fixes would be really annoying for players in particular.

**Comment by czyzby** [comment]
It's OK to request updates in issues, I'll update the default library versions asap.

**Comment by czyzby** [comment]
@tommyettinger Any updates on this? To be honest, the "simple" example is already pretty great and a link to your documentation should be enough for most people interested in grid-based games. If you lack the time to create an even more advanced template, I can close this issue.

**Comment by tommyettinger** [comment]
Sure, feel free to close; I can't think of much to put in the advanced demo that is short of a full game. I'm trying to figure out how to best publish javadocs for this, and I really need to add a decent wiki article for how to go ahead from the starting point. The next version should be out soon; the biggest change is that there's a third, optional, module in SquidLib that relies on LibGDX like the display module, but doesn't specify how the game should look like the text-based display does. It's for serializing save data in a way that works on desktop, android, and GWT, and GWT can only save Strings (to Preferences). This does compress the strings, though, using a tiny library that is on Maven Central. When I release the the next version I will provide all the dependency info.

I also need to figure out how to handle the assets, which SquidLib used to pack in the display module's jar, but now doesn't so users can use only what they need. **Is there a way you are aware of to give a link, such as for documentation or links to additional assets, to users of the setup tool?** Ideally it would only give the links for the appropriate projects, so this would only print the links to SquidLib's font and icon assets if `squidlib`, which is the display module, was selected. I could also stick the links at the top of the demo sources, or in a separate file, but there's a good chance they'll be missed.

**Comment by czyzby** [comment]
It's OK. I'd appreciate if you commented in this issue once you're done releasing the next version.

Well, there's a link to the project next to each third-party library. I'm pretty sure anyone interested in your libraries is likely to click these, so it might be a matter of cleaning up your README (it seems that it contains a lot of legacy data, kind of like a change log) and including the assets-related info there. We could also add a link to your wiki inside a comment of your project template and inside the generated `README.md` file.

**Comment by tommyettinger** [comment]
I'm pretty late on this, but I just updated SquidLib to 3.0.0-b8 and the demo is significantly updated as well.
I'm not sure what the best way to give the dependency info is, because there are 3 parts to SquidLib, but I'd only consider 2 to be reasonable as options during project creation. What I think the info needed is:
- (should go in the list) [squidlib-util 3.0.0-b8](http://search.maven.org/#artifactdetails%7Ccom.squidpony%7Csquidlib-util%7C3.0.0-b8%7Cjar) "Logic, content generation, and AI for grid-based games such as roguelikes" ; GWT inherits value: <inherits name="squidlib-util" />
  - depends on [regexodus 1.9](http://search.maven.org/#artifactdetails%7Ccom.github.tommyettinger%7Cregexodus%7C0.1.9%7Cjar)
- (should go in the list) [squidlib 3.0.0-b8](http://search.maven.org/#artifactdetails%7Ccom.squidpony%7Csquidlib%7C3.0.0-b8%7Cjar) "Support for text-based display common in roguelike games" ; GWT inherits value: <inherits name="squidlib" />
  - (depends on libGDX 1.9.3; both newer versions have bugs that affect this code, 1.9.4 just visually, but 1.9.5 doesn't work on GWT at all, and the snapshots aren't an option for code that goes on Maven Central).
  - [squidlib-util 3.0.0-b8](http://search.maven.org/#artifactdetails%7Ccom.squidpony%7Csquidlib-util%7C3.0.0-b8%7Cjar)
    - depends on [regexodus 1.9](http://search.maven.org/#artifactdetails%7Ccom.github.tommyettinger%7Cregexodus%7C0.1.9%7Cjar)
- (may go in the list) [regexodus 1.9](http://search.maven.org/#artifactdetails%7Ccom.github.tommyettinger%7Cregexodus%7C0.1.9%7Cjar) "Regular expressions that work on GWT the same as on desktop and Android" ; GWT inherits value: `<inherits name="regexodus"/>`

The current gdx-setup seems to have some of the dependencies for the earlier versions ordered strangely, if I remember it right. There was a relatively minor issue where adding a dependency to one of the components didn't add dependencies to one of the ones it needed, and it either didn't add a dependency on regexodus or added a dependency to squidlib even if it shouldn't have been selected. 
To be clear, squidlib depends on squidlib-util, but squidlib-util can be used without squidlib. They all need regexodus. Gradle should be able to handle most of this on its own (just not on GWT).

The basic demo is at https://github.com/tommyettinger/SquidLib-Demos/tree/master/GdxSetup/3.0.0-b8 , and I don't know what further formatting it needs. The original project was created with the latest nightly of gdx-setup, and dependencies on squidlib, squidlib-util, and regexodus were added, with the demo code mostly rewritten/cleaned up since the last version. I have verified that Android and GWT work here.

There was a b7 release but it was broken on GWT, so I quickly pushed a b8 with that and one other bug fixed.

**Comment by czyzby** [comment]
Thanks, I'll try to update the demo next weekend.

**Comment by czyzby** [comment]
To be honest, the current demo is very similar in terms of functionality, works with your latest library version and looks much better. I don't know if it's just me or if that's just he fonts, but your previous  demo has this sort of a nice console feel. In the new version the `@` character seems off and more like a drawn sprite than text, a non-monospaced font is used and the bottom of the screen and the walls are gone. I'll just leave the current demo as is and if you want to showcase some latest API, I'd revert to the previous look first.

**Comment by tommyettinger** [comment]
It's possible that's an asset thing and it's using the libgdx default font because it can't find the requested .fnt file (they aren't bundled in the lib any more, to avoid bloating the jar where they can' be removed if unused). I think I linked at the top of the demo's source to the exact paths to the files that demo needs if you want to include them, or there could be some step in Gradle setup to download them somehow? It sounds like this is the case because the default font doesn't have any of the chars used for walls, and is variable-width; it's only used as a fallback if no fonts requested can be found, since that version of Arial is included in libGDX.

The files needed in the assets directory are available at:

https://raw.githubusercontent.com/SquidPony/SquidLib/v3.0.0-b8/assets/Inconsolata-LGC-Custom-distance.fnt

https://raw.githubusercontent.com/SquidPony/SquidLib/v3.0.0-b8/assets/Inconsolata-LGC-Custom-distance.png

I could be wrong and there could be some other issue at work here.

**Comment by czyzby** [comment]
Yeah, I must have run incorrect project after cloning the demos. `3.0.0b-8` works as expected, I'll update the demo soon.

**Comment by czyzby** [comment]
Try downloading the latest runnable (link in the description) and check if it's OK.

**Comment by tommyettinger** [comment]
Works great! Thanks for handling this. I had one small issue (that I think was an IntelliJ IDEA bug) when using auto-import, which made the imported project consider any sub-modules to be ordinary folders without source or projects in them. I re-imported the project with auto-import off and it works like a charm. The assets load successfully, although there was a small comment at the top of the demo with links to where to get other assets compatible with this, and that seems to have been removed at some point. If you want to add that comment back in, it should say,

```
/*
This demo needs these files in your project's assets folder:

https://raw.githubusercontent.com/SquidPony/SquidLib/v3.0.0-b8/assets/Inconsolata-LGC-Custom-distance.fnt
https://raw.githubusercontent.com/SquidPony/SquidLib/v3.0.0-b8/assets/Inconsolata-LGC-Custom-distance.png

They may be there already, since gdx-setup includes them with this demo; if they aren't, you should download them to that directory to have the font show up correctly.
If you want other fonts or resources that SquidLib can easily load, you can get the whole bunch in a zip:

https://raw.githubusercontent.com/SquidPony/SquidLib/v3.0.0-b8/assets.zip

And then delete or move any files you don't need from there out of the assets folder.
*/
```
