### ISSUE TITLE
Unable to run android project on real devices

### ISSUE THREAD

**Issue by WimpyMistake** [czyzby/gdx-setup#34]
I downloaded latest version from this link https://dl.kotcrab.com/libgdx/gdx-setup-latest.jar.
Generated a project with core, desktop, android backends.
Choose Viseditor from third-party tab.
Choose Basic VisEditor from template.
Project generated successfully.
Able to run the desktop project.
But when running android project with real device (adb debugging ON), receive this error from logcat http://pastebin.com/bRzGSmkM
(i guess its because no asset folder in android project)

im using MacOs Yosemite, Eclipse Mars.2

**Comment by WimpyMistake** [comment]
Update:
Running via gradle task works. It just running as Android Application by right-clicking android project in Eclipse doesn't work

**Comment by czyzby** [comment]
This is because Gradle defines where the assets folder is located and Eclipse (with its plugin) probably does not check its data. I had no problems running the project on a real device via IntelliJ/Android Studio. I'd check the Eclipse plugin settings for this particular project - maybe there's a way to define custom path to Android application assets. I think that keeping assets in a separate "module" is the sensible thing to do, and I'd rather not move it back to Android subproject - it makes adding new subprojects messier.
