### ISSUE TITLE
Add Artemis-odb extension

### ISSUE THREAD

**Issue by kotcrab** [czyzby/gdx-setup#4]
[Artemis-odb](https://github.com/junkdog/artemis-odb) is an alternative to libgdx's Ashley. Definitely worth including.

**Comment by czyzby** [comment]
Note that VisEditor includes Artemis dependencies manually. Remove Artemis-related code from VisEditor runtime extension and replace with `Artemis().initiate(project)`. If you need a specific version to make sure that VisEditor works properly, you can override `artemisVersion` property *after* invoking its `initiate` method.

**Comment by kotcrab** [comment]
If I do it this way then I will end up with duplicated `net.onedaybeard.artemis:artemis-odb` core dependency (it will be included for the second time from `vis-runtime` itself). I understand that this won't make any difference but there maybe situation where user would want to update Artemis version and will look at their `build.gradle` and may try to change its version there - which is wrong and could lead to RuntimeExceptions due to version mismatch with Artemis used by `vis-rutnime`. In this case I think it would be better to just leave it duplicated.

**Comment by czyzby** [comment]
I meant that there will be no duplicated `net.onedaybeard.artemis:artemis-odb` lines one after another in Gradle files. I think you mean that there might be version *conflicts*.

If the user chooses another Artemis version than the one referenced by VisRuntime, Gradle will resolve this by choosing the newer library (I think this is the default behavior).

However, library versions are taken directly from the `extensions.lml` screen widgets. When you use `Artemis().initiate(project)`, it might extract the newest version (1.4.something?) rather than 1.2.1 - even though Artemis was not explicitly selected by the user.

You could include a workaround where you check if Artemis library is selected on the screen. If not, force a specific Artemis version with `project.properties["artemisVersion"] = "1.2.1"`. You can add whatever methods you need to `extensions.kt` (like `return thirdPartyVersions[libId].isChecked`) to pull this off.

**Comment by kotcrab** [comment]
I meant that including `net.onedaybeard.artemis:artemis-odb` is not required at all for `vis-runtime`. Because `vis-runtime` already [includes it](https://github.com/kotcrab/vis-editor/blob/master/build.gradle#L97).

Using `Artemis().initiate(project)` would create dependency tree like this:
```
- VisRuntime
    \- Artemis
- Artemis
```
Well, this could lead to version conflict in the future if user changes second version of included Artemis. `vis-runtime` only needs the GWT part of Artemis dependencies (not even the GWT inherit). I'll try experimenting with it more.

**Comment by czyzby** [comment]
Nonetheless, GWT requires its sources, so you have to include the dependencies explicitly at some point. You could leave it as-is (include only Artemis sources in GWT, before checking if Artemis isn't already included) if the conflict is bothering you, but - well - I think that's a pretty common situation. Don't forget that *most* of third-party libraries depend on an old LibGDX version and applications still work as they should.

**Comment by kotcrab** [comment]
> Gradle will resolve this by choosing the newer library (I think this is the default behavior).

This is correct.

>Don't forget that most of third-party libraries depend on an old LibGDX version and applications still work as they should.

Yeah you are right, I'm probably being too nitpicking here.

With the current solution it works properly when both extensions are selected. Version forced by VisRuntime will be used but I don't know if you like this solution. It's fragile because it depends on order in which extensions are defined in `thirdPartyExtensions.kt`.

If both extensions are checked Artemis is evaluated first then VisRuntime is evaluated so it can override Artemis version to correct one. Note that this won't work if VisRuntime is defined first.

Workaround by checking if Artemis is already selected would be depending in the same way on the extension order as this solution - unless I am missing something and you wanted to include it outside extension definitions.

**Comment by czyzby** [comment]
I don't think it's much of an issue. Anyone using VisEditor is probably aware that it uses Artemis internally and will not add this dependency - we can even include a simple message (in tooltip) that VisRuntime also initiates Artemis ODB.
